logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: TRACE
    gateway.http: DEBUG

gateway:
  logging:
    enabled: true
    log-headers: true
    log-body: true
    max-body-size: 2048

spring:
  cloud:
    gateway:
      server:
        webflux:
          trusted-proxies: ".*"

management:
  tracing:
    sampling:
      probability: 1.0
