logging:
  level:
    root: ${LOG_LEVEL:DEBUG}

spring:
  cloud:
    gateway:
      server:
        webflux:
          trusted-proxies: "${TRUSTED_PROXIES:10\\..*|172\\..*|192\\.168\\..*}"

management:
  tracing:
    sampling:
      probability: 1.0
