package com.acs.common.jwt;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class JwtTokenProviderTest {

    private static final String SECRET =
            "ThisIsATestSecretKeyForHS512AlgorithmThatMustBeAtLeastSixtyFourBytesLong!!";

    private JwtTokenProvider provider;

    @BeforeEach
    void setUp() {
        provider = new JwtTokenProvider(SECRET);
    }

    @Test
    void generateAndParseToken() {
        GatewayTokenPayload payload = new GatewayTokenPayload(
                null,
                "EMP001",
                "portal",
                List.of("portal", "admin"),
                Instant.now().truncatedTo(ChronoUnit.SECONDS),
                Instant.now().plusSeconds(3600).truncatedTo(ChronoUnit.SECONDS)
        );

        String token = provider.generateToken(payload);
        assertNotNull(token);
        assertFalse(token.isBlank());

        GatewayTokenPayload parsed = provider.parsePayload(token);
        assertNotNull(parsed.jti());
        assertEquals("EMP001", parsed.employeeNumber());
        assertEquals("portal", parsed.requestApp());
        assertEquals(List.of("portal", "admin"), parsed.allowedApps());
        assertEquals(payload.issuedAt(), parsed.issuedAt());
        assertEquals(payload.expiration(), parsed.expiration());
    }

    @Test
    void jtiIsAutoGenerated() {
        GatewayTokenPayload payload = new GatewayTokenPayload(
                "should-be-ignored",
                "EMP002",
                "app1",
                List.of("app1"),
                Instant.now().truncatedTo(ChronoUnit.SECONDS),
                Instant.now().plusSeconds(3600).truncatedTo(ChronoUnit.SECONDS)
        );

        String token = provider.generateToken(payload);
        GatewayTokenPayload parsed = provider.parsePayload(token);

        assertNotEquals("should-be-ignored", parsed.jti());
        assertEquals(36, parsed.jti().length()); // UUID format
    }

    @Test
    void validateToken_valid() {
        GatewayTokenPayload payload = new GatewayTokenPayload(
                null, "EMP001", "app1", List.of("app1"),
                Instant.now(), Instant.now().plusSeconds(3600)
        );

        String token = provider.generateToken(payload);
        assertTrue(provider.validateToken(token));
    }

    @Test
    void validateToken_tampered() {
        GatewayTokenPayload payload = new GatewayTokenPayload(
                null, "EMP001", "app1", List.of("app1"),
                Instant.now(), Instant.now().plusSeconds(3600)
        );

        String token = provider.generateToken(payload);
        String tampered = token.substring(0, token.length() - 5) + "XXXXX";
        assertFalse(provider.validateToken(tampered));
    }

    @Test
    void validateToken_expired() {
        GatewayTokenPayload payload = new GatewayTokenPayload(
                null, "EMP001", "app1", List.of("app1"),
                Instant.now().minusSeconds(7200),
                Instant.now().minusSeconds(3600)
        );

        String token = provider.generateToken(payload);
        assertFalse(provider.validateToken(token));
    }

    @Test
    void validateToken_wrongSecret() {
        GatewayTokenPayload payload = new GatewayTokenPayload(
                null, "EMP001", "app1", List.of("app1"),
                Instant.now(), Instant.now().plusSeconds(3600)
        );

        String token = provider.generateToken(payload);

        JwtTokenProvider otherProvider = new JwtTokenProvider(
                "AnotherSecretKeyForTestingPurposesThatIsAlsoAtLeastSixtyFourBytesLongOK!!");
        assertFalse(otherProvider.validateToken(token));
    }
}
