CREATE TABLE IF NOT EXISTS PROPERTIES (
    ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPLICATION     VARCHAR(128)    NOT NULL,
    PROFILE         VARCHAR(128)    NOT NULL,
    LABEL           VARCHAR(128)    NOT NULL,
    PROP_KEY        VARCHAR(256)    NOT NULL,
    PROP_VALUE      VARCHAR(4000),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
