CREATE TABLE PROPERTIES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPLICATION     VARCHAR2(128)   NOT NULL,
    PROFILE         VARCHAR2(128)   NOT NULL,
    LABEL           VARCHAR2(128)   NOT NULL,
    PROP_KEY        VARCHAR2(256)   NOT NULL,
    PROP_VALUE      VARCHAR2(4000),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
